### ISSUE TITLE
How to add Data Nodes in the EFK Cluster?

### ISSUE THREAD

**Issue by rileyhun** [Sudharma/efk-k8s#1]
Hello - 

Thanks for this useful helm chart. The security protocols are exactly what I needed and I can integrate vault secrets from Google Secret Manager. Is this set-up production-ready or would you recommend we have 1 master nodes and 3 replicas of data nodes? If the latter, how do we implement that using your helm chart?

For example,

I tried adding this to the `values.yaml` but it didn't work:

```
elasticsearch:
  clusterName: "elasticsearch"
  nodeGroup: "master"

  masterService: "elasticsearch-master"

  # Elasticsearch roles that will be applied to this nodeGroup
  # These will be set as environment variables. E.g. node.master=true
  roles:
    master: "true"
    ingest: "true"
    data: "true"
    remote_cluster_client: "true"
```

Thanks,

Riley
